from wikibase_api.utils.exceptions import ApiError, AuthError
from wikibase_api.wikibase_api import Wikibase

__all__ = ["AuthError", "ApiError", "Wikibase"]
